#run binmt.py
name: Auto Sign
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run binmt.py
        env:
          GitHub_Actions: true
        run: |
          python binmt.py